name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis. Needed for the versioning step.
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node setVersion.js
    - run: npm run build --if-present
    - run: xvfb-run -a npm test
    
    # Only run the following steps for the latest Node.js version. Note this uses VSCE
    - name: compile and create vsix
      if: matrix.node-version == '22.x'
      run: npm run package
          
    - name: Upload VSIX to artifacts
      if: matrix.node-version == '22.x'
      uses: actions/upload-artifact@v4
      with:
        name: CopilotStudioVsixPackage
        path: "*.vsix"