name: Pull Request Build and Test

on:
  pull_request:
    branches:
      - main

env:
  BuildConfiguration: Debug
  BuildProjectFile: src/build.proj

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: (github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name) && (github.event_name == 'pull_request')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: dotnet restore
        run: |
          dotnet restore ${{ env.BuildProjectFile }}

      - name: dotnet build
        run: |
          dotnet build ${{ env.BuildProjectFile }} --no-restore --configuration ${{ env.BuildConfiguration }} -p:langversion=preview

      - name: dotnet test
        run: |
          dotnet test ${{ env.BuildProjectFile }} --no-build --no-restore --configuration ${{ env.BuildConfiguration }} --logger trx --collect "Code coverage" --results-directory ${{ github.workspace }}/TestResults --blame

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Test Results
          path: ${{ github.workspace }}/TestResults/**/*.trx
          reporter: dotnet-trx
